# Travis-CI for Pyslvs-UI
language: python
os: linux
dist: xenial

jobs:
  include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"

before_install:
  - python3 -m pip install pip setuptools -U
  - python3 -m pip install -e . -U

script:
  - bash ./scripts/appimage_recipe.sh

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
