# Travis-CI for Pyslvs-UI
language: python

git:
  depth: 1

matrix:
  include:
    - &linux
      os: linux
      sudo: required
      python: "3.7"
      dist: xenial
      before_install:
        - python3 -m pip install -r requirements.txt -U
      install:
        - make
        - cd pyslvs; python3 setup.py install; cd -
        - python3 setup.py install
      after_success: &pypi-deploy
        # PyPI deployment
        - if [[ "$TRAVIS_REPO_SLUG" == "KmolYuan/Pyslvs-UI" && -n "$TRAVIS_TAG" ]]; then
          python3 -m pip install twine;
          python3 setup.py bdist_wheel;
          python3 -m twine upload dist/*.whl --skip-existing;
          fi
      deploy:
        - &executable-deploy
          provider: releases
          overwrite: true
          api_key: $TRAVIS_TOKEN
          file_glob: true
          file: out/pyslvs*.AppImage
          skip_cleanup: true
          on:
            tags: true

    - <<: *linux
      python: "3.8-dev"
      addons:
        apt:
          update: true
          packages:
            - libhdf5-dev

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=3.7.0
      before_install:
        - git submodule update --init
        - git submodule update --init --recursive pyslvs
        - brew update
        - brew upgrade pyenv
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${PYTHON}
        - pyenv global ${PYTHON}
        - python3 -m pip install pip -U
        - python3 -m pip install https://github.com/pyinstaller/pyinstaller/tarball/develop
        - pyenv rehash
        - python3 --version
        - python3 -m pip --version
        - pyinstaller --version
        - python3 -m pip install -r requirements.txt -U
      install:
        - make
        - python3 setup.py install
        - pyenv rehash
      after_success: *pypi-deploy
      deploy:
        - <<: *executable-deploy
          file: dist/pyslvs*.app.zip

script:
  - pyslvs --test

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
