# AppVeyor for Pyslvs-UI
image: Visual Studio 2017

platform:
    - x64

environment:
    matrix:

        - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
          MSYS_DIR: &msys2 C:\msys64
          PYTHON_DIR: C:\Python37-x64

install:
    # Environment variables.
    - set Path=%PYTHON_DIR%;%Path%
    - set Path=%PYTHON_DIR%\Scripts;%Path%
    - set Path=%MSYS_DIR%\usr\bin;%Path%
    - set Path=%MINGW_DIR%\mingw64\bin;%Path%

    # Show Python.
    - python --version
    - pip --version

    # Set Python compiler to Msys2.
    - echo [build]>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
    - echo compiler = mingw32>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
    - patch %PYTHON_DIR%\lib\distutils\cygwinccompiler.py platform\patch.diff
    - copy %PYTHON_DIR%\vcruntime140.dll %PYTHON_DIR%\libs

    # Install modules.
    - pip install -r requirements.txt
    - pip install pyinstaller

    # Show tool kits.
    - pyinstaller --version
    - gcc --version
    - mingw32-make --version

before_build:
    # Clone submodules.
    - git submodule update --init --recursive

build_script:
    - mingw32-make

test: off

artifacts:
    - path: dist/pyslvs-*.exe
      name: pyslvs

deploy:
    - release: Pyslvs $(APPVEYOR_REPO_TAG_NAME)
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: ""
      provider: GitHub
      auth_token: $(APPVEYOR_TOKEN)
      artifacts: pyslvs
      force_update: true
      on:
          appveyor_repo_tag: true
          PYTHON_DIR: C:\Python37-x64
